language: python
python:
  - '2.7'
  - '3.3'
#  - 'pypy'

# Install system dependencies
before_install:
  - 'travis_retry sudo apt-get install python-dev libevent-dev'

# Install python dependencies
install:
  - 'travis_retry pip install -U -e ".[test]" --use-mirrors'
  - 'travis_retry pip install coveralls --use-mirrors'

# Blacklist legacy branches as they don't have operating tests
branches:
  except:
    - legacy/armet
    - legacy/flapjack

# Run tests
script: 'py.test --pep8 --cov armet'
after_success: 'coveralls'
